# Form implementation generated from reading ui file 'addAlarm.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.
import os

from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import QUrl, pyqtSignal
from PyQt6.QtMultimedia import QMediaPlayer, QAudioOutput
from PyQt6.QtWidgets import QFileDialog, QDialog

# переопределяем клас QtWidgets.QSpinBox для вывода занчений типа 01, 02, ...
class ZeroPaddedSpinBox(QtWidgets.QSpinBox):
    def textFromValue(self, value: int) -> str:
        return f"{value:02d}"


class U_Dialog(QDialog):
    value_selected = pyqtSignal(tuple)  # Определение сигнала
    
    def __init__(self, name_alarm, week, time_al):
        super().__init__()
        self.name_alarm = name_alarm
        self.week = week
        self.t_h = int(time_al[:2])
        self.t_s = int(time_al[3:])
        self.resize(436, 364)
        self.setMinimumSize(QtCore.QSize(0, 0))
        self.setMaximumSize(QtCore.QSize(436, 365))
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel()
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel()
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit()
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButton_9 = QtWidgets.QPushButton()
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout.addWidget(self.pushButton_9)
        self.spinBox = QtWidgets.QSpinBox()
        self.spinBox.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.spinBox.setFont(font)
        self.spinBox.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.spinBox.setMouseTracking(True)
        self.spinBox.setWrapping(False)
        self.spinBox.setFrame(False)
        self.spinBox.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.spinBox.setKeyboardTracking(True)
        self.spinBox.setProperty("showGroupSeparator", False)
        self.spinBox.setSuffix("")
        self.spinBox.setPrefix("")
        self.spinBox.setMaximum(23)
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout.addWidget(self.spinBox)
        
        # подмена старого spinBox на новый определенный в классе ZeroPaddedSpinBox
        old = self.spinBox
        layout = self.verticalLayout  # ← ВАЖНО
        
        new = ZeroPaddedSpinBox(self)
        new.setRange(old.minimum(), old.maximum())
        new.setValue(old.value())
        new.setFont(old.font())
        new.setAlignment(old.alignment())
        new.setButtonSymbols(old.buttonSymbols())
        new.setMaximum(old.maximum())
        new.setMinimum(old.minimum())
        new.setFrame(old.hasFrame())
        
        layout.replaceWidget(old, new)
        old.deleteLater()
        
        self.spinBox = new  # ← обязательно!
        
        self.pushButton_10 = QtWidgets.QPushButton()
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout.addWidget(self.pushButton_10)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.label_4 = QtWidgets.QLabel()
        self.label_4.setMinimumSize(QtCore.QSize(0, 0))
        self.label_4.setMaximumSize(QtCore.QSize(32, 16777215))
        font = QtGui.QFont()
        font.setPointSize(35)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton_11 = QtWidgets.QPushButton()
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setObjectName("pushButton_11")
        self.verticalLayout_2.addWidget(self.pushButton_11)
        self.spinBox_2 = QtWidgets.QSpinBox()
        self.spinBox_2.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.spinBox_2.setFont(font)
        self.spinBox_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.IBeamCursor))
        self.spinBox_2.setMouseTracking(True)
        self.spinBox_2.setWrapping(False)
        self.spinBox_2.setFrame(False)
        self.spinBox_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.spinBox_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.spinBox_2.setKeyboardTracking(True)
        self.spinBox_2.setProperty("showGroupSeparator", False)
        self.spinBox_2.setSuffix("")
        self.spinBox_2.setPrefix("")
        self.spinBox_2.setMaximum(59)
        self.spinBox_2.setObjectName("spinBox_2")
        self.verticalLayout_2.addWidget(self.spinBox_2)
        
        # подмена старого spinBox на новый определенный в классе ZeroPaddedSpinBox
        old = self.spinBox_2
        layout = self.verticalLayout_2  # ← ВАЖНО
        
        new = ZeroPaddedSpinBox(self)
        new.setRange(old.minimum(), old.maximum())
        new.setValue(old.value())
        new.setFont(old.font())
        new.setAlignment(old.alignment())
        new.setButtonSymbols(old.buttonSymbols())
        new.setMaximum(old.maximum())
        new.setMinimum(old.minimum())
        new.setFrame(old.hasFrame())
        
        layout.replaceWidget(old, new)
        old.deleteLater()
        
        self.spinBox_2 = new  # ← обязательно!
        
        self.pushButton_12 = QtWidgets.QPushButton()
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setObjectName("pushButton_12")
        self.verticalLayout_2.addWidget(self.pushButton_12)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_1 = QtWidgets.QPushButton()
        self.pushButton_1.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_1.setObjectName("pushButton_1")
        self.horizontalLayout_2.addWidget(self.pushButton_1)
        self.pushButton_2 = QtWidgets.QPushButton()
        self.pushButton_2.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton()
        self.pushButton_3.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton()
        self.pushButton_4.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton()
        self.pushButton_5.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_2.addWidget(self.pushButton_5)
        self.pushButton_6 = QtWidgets.QPushButton()
        self.pushButton_6.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_2.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton()
        self.pushButton_7.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_2.addWidget(self.pushButton_7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.input_play_Button = QtWidgets.QPushButton()
        self.input_play_Button.setObjectName("input_play_Button")
        self.horizontalLayout_4.addWidget(self.input_play_Button)
        self.stop_play_Button = QtWidgets.QPushButton()
        self.stop_play_Button.setObjectName("stop_play_Button")
        self.horizontalLayout_4.addWidget(self.stop_play_Button)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_3.addItem(spacerItem3)
        self.ok_Button = QtWidgets.QPushButton()
        self.ok_Button.setObjectName("ok_Button")
        self.verticalLayout_3.addWidget(self.ok_Button)
        spacerItem4 = QtWidgets.QSpacerItem(20, 27, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem4)
        self.verticalLayout_4.addLayout(self.verticalLayout_3)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)
        
        # предустановленная мелодия
        self.music = '1.mp3'
        # если предустановленной мелодии не существует не позволяем ее оставить без выбора
        if not os.path.exists(self.music):
            self.ok_Button.setEnabled(False)
        # вызовы на кнопки
        self.input_play_Button.clicked.connect(self.open_modal)  # выбор музыки
        self.stop_play_Button.clicked.connect(self.music_stop)  # останов музыки
        self.stop_play_Button.setEnabled(
            False)  # пока не произошел выбор и не начала играть музыка, то не можем ее остановить
        self.ok_Button.clicked.connect(self.handle_button_click)  # выход в основное окно
        
        self.pushButton_9.clicked.connect(self.add_h)
        self.pushButton_10.clicked.connect(self.del_h)
        self.pushButton_11.clicked.connect(self.add_m)
        self.pushButton_12.clicked.connect(self.del_m)
        
        
        # self.week = {1: False, 2: False, 3: False, 4: False, 5: False, 6: False, 7: False}
        self.pushButton_1.clicked.connect(lambda x: self.button_clicked(1))
        self.pushButton_2.clicked.connect(lambda x: self.button_clicked(2))
        self.pushButton_3.clicked.connect(lambda x: self.button_clicked(3))
        self.pushButton_4.clicked.connect(lambda x: self.button_clicked(4))
        self.pushButton_5.clicked.connect(lambda x: self.button_clicked(5))
        self.pushButton_6.clicked.connect(lambda x: self.button_clicked(6))
        self.pushButton_7.clicked.connect(lambda x: self.button_clicked(7))

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Добавление будильника"))
        self.label.setText(_translate("Dialog", "Установить будильник"))
        self.lineEdit.setText(_translate("Dialog", self.name_alarm))
        
        self.label_2.setText(_translate("Dialog", "Название"))
        self.pushButton_9.setText(_translate("Dialog", "+"))
        self.pushButton_10.setText(_translate("Dialog", "-"))
        self.label_4.setText(_translate("Dialog", ":"))
        self.pushButton_11.setText(_translate("Dialog", "+"))
        self.pushButton_12.setText(_translate("Dialog", "-"))
        self.pushButton_1.setText(_translate("Dialog", "Пн"))
        self.pushButton_2.setText(_translate("Dialog", "Вт"))
        self.pushButton_3.setText(_translate("Dialog", "Ср"))
        self.pushButton_4.setText(_translate("Dialog", "Чт"))
        self.pushButton_5.setText(_translate("Dialog", "Пн"))
        self.pushButton_6.setText(_translate("Dialog", "Сб"))
        self.pushButton_7.setText(_translate("Dialog", "Вс"))
        self.input_play_Button.setText(_translate("Dialog", "Задать музыку и воспроизвести"))
        self.stop_play_Button.setText(_translate("Dialog", "Остановить музыку"))
        self.ok_Button.setText(_translate("Dialog", "Подтвердить"))
        for i, j in  enumerate(self.week):
            if j:
                button_name = f"pushButton_{i+1}"
                button = getattr(self, button_name)
                button.setStyleSheet("background-color: green;")
        self.spinBox.setValue(int(self.t_h))
        self.spinBox_2.setValue(int(self.t_s))
        
                
        
        
    def add_h(self):
        self.spinBox.stepUp()
    def del_h(self):
        self.spinBox.stepDown()
    def add_m(self):
        self.spinBox_2.stepUp()
    def del_m(self):
        self.spinBox_2.stepDown()
        
    def button_clicked(self, f):
        button_name = f"pushButton_{f}"
        # Получаем ссылку на объект кнопки
        button = getattr(self, button_name)
        
        if self.week[f-1]:
            self.week[f-1] = False
            button.setStyleSheet("")
        else:
            self.week[f-1] = True
            button.setStyleSheet("background-color: green;")
        print(self.week)
        
        # Вызов модального окна проигрования музыки с передачей имени проигруемого файла
    
    def open_modal(self):
        self.music = QFileDialog.getOpenFileName(self, 'Open File', './', 'JPG File (*.mp3);;MP3 File (*.mp3)')[0]
        print(self.music)
        file_path = self.music  # "path/to/your/file.mp3"  # Путь к вашему MP3-файлу
        self.player = QMediaPlayer(self)
        self.audio_output = QAudioOutput(self)
        self.player.setAudioOutput(self.audio_output)
        self.player.setSource(QUrl.fromLocalFile(file_path))
        self.audio_output.setVolume(50)
        self.player.play()  # Воспроизведение аудио
        self.player.mediaStatusChanged.connect(self.handle_media_status)
        # делаеам активные и неактивные кнопки
        self.stop_play_Button.setEnabled(True)
        self.ok_Button.setEnabled(False)
        
        # подтверждаем значения и выходим
    
    def handle_button_click(self):
        # Ваше выбранное значение
        selected_value = (self.lineEdit.text(), self.spinBox.text(), self.spinBox_2.text(), self.week, self.music)
        self.value_selected.emit(selected_value)  # Испускание сигнала с передачей значения
        self.accept()  # Закрываем окно
        
        # останавливаем воспроизведение музыки
    
    def music_stop(self):
        self.player.stop()
        self.ok_Button.setEnabled(True)
        
        # Проверяем статус воспроизведения музыки(если музыка закончилась - разблокируем кнопки)
    
    def handle_media_status(self, status):
        if status == QMediaPlayer.MediaStatus.EndOfMedia:
            self.ok_Button.setEnabled(True)
        
    
    
    

if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = U_Dialog("Example",[False, True, False, False, False, False, False], "12:00")
    window.show()
    sys.exit(app.exec())
