#

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(516, 650)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_Alarm = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_Alarm.setMinimumSize(QtCore.QSize(0, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_Alarm.setFont(font)
        self.pushButton_Alarm.setObjectName("pushButton_Alarm")
        self.horizontalLayout.addWidget(self.pushButton_Alarm)
        self.pushButton_Timer = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_Timer.setMinimumSize(QtCore.QSize(128, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_Timer.setFont(font)
        self.pushButton_Timer.setStyleSheet("background-color: rgb(192, 191, 188);")
        self.pushButton_Timer.setObjectName("pushButton_Timer")
        self.horizontalLayout.addWidget(self.pushButton_Timer)
        self.pushButton_Sec = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_Sec.setMinimumSize(QtCore.QSize(128, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_Sec.setFont(font)
        self.pushButton_Sec.setObjectName("pushButton_Sec")
        self.horizontalLayout.addWidget(self.pushButton_Sec)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pushButton_Alarm_add = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_Alarm_add.setMinimumSize(QtCore.QSize(99, 35))
        self.pushButton_Alarm_add.setObjectName("pushButton_Alarm_add")
        self.verticalLayout.addWidget(self.pushButton_Alarm_add)
        self.scrollArea_Alarm = QtWidgets.QScrollArea(parent=Dialog)
        self.scrollArea_Alarm.setMinimumSize(QtCore.QSize(0, 250))
        self.scrollArea_Alarm.setWidgetResizable(True)
        self.scrollArea_Alarm.setObjectName("scrollArea_Alarm")
        self.scrollAreaWidgetContents_Alarm = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_Alarm.setGeometry(QtCore.QRect(0, 0, 442, 514))
        self.scrollAreaWidgetContents_Alarm.setObjectName("scrollAreaWidgetContents_Alarm")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_Alarm)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_Alarm1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Alarm1.setObjectName("horizontalLayout_Alarm1")
        self.verticalLayout_Alarm = QtWidgets.QVBoxLayout()
        self.verticalLayout_Alarm.setObjectName("verticalLayout_Alarm")
        self.label_name = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_Alarm)
        self.label_name.setMinimumSize(QtCore.QSize(355, 0))
        self.label_name.setMaximumSize(QtCore.QSize(355, 16777215))
        self.label_name.setObjectName("label_name")
        self.verticalLayout_Alarm.addWidget(self.label_name)
        self.pushButton_ch_Alarm = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents_Alarm)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.pushButton_ch_Alarm.setFont(font)
        self.pushButton_ch_Alarm.setObjectName("pushButton_ch_Alarm")
        self.verticalLayout_Alarm.addWidget(self.pushButton_ch_Alarm)
        self.horizontalLayout_Alarm2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_Alarm2.setObjectName("horizontalLayout_Alarm2")
        self.label_d1 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_Alarm)
        self.label_d1.setMinimumSize(QtCore.QSize(28, 0))
        self.label_d1.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_d1.setObjectName("label_d1")
        self.horizontalLayout_Alarm2.addWidget(self.label_d1)
        self.label_d2 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_Alarm)
        self.label_d2.setMinimumSize(QtCore.QSize(28, 0))
        self.label_d2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_d2.setObjectName("label_d2")
        self.horizontalLayout_Alarm2.addWidget(self.label_d2)
        self.label_d3 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_Alarm)
        self.label_d3.setMinimumSize(QtCore.QSize(28, 0))
        self.label_d3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_d3.setObjectName("label_d3")
        self.horizontalLayout_Alarm2.addWidget(self.label_d3)
        self.label_d4 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_Alarm)
        self.label_d4.setMinimumSize(QtCore.QSize(28, 0))
        self.label_d4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_d4.setObjectName("label_d4")
        self.horizontalLayout_Alarm2.addWidget(self.label_d4)
        self.label_d5 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_Alarm)
        self.label_d5.setMinimumSize(QtCore.QSize(28, 0))
        self.label_d5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_d5.setObjectName("label_d5")
        self.horizontalLayout_Alarm2.addWidget(self.label_d5)
        self.label_d6 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_Alarm)
        self.label_d6.setMinimumSize(QtCore.QSize(28, 0))
        self.label_d6.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_d6.setObjectName("label_d6")
        self.horizontalLayout_Alarm2.addWidget(self.label_d6)
        self.label_d7 = QtWidgets.QLabel(parent=self.scrollAreaWidgetContents_Alarm)
        self.label_d7.setMinimumSize(QtCore.QSize(28, 0))
        self.label_d7.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_d7.setObjectName("label_d7")
        self.horizontalLayout_Alarm2.addWidget(self.label_d7)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_Alarm2.addItem(spacerItem3)
        self.pushButton_AlarmDel = QtWidgets.QPushButton(parent=self.scrollAreaWidgetContents_Alarm)
        self.pushButton_AlarmDel.setObjectName("pushButton_AlarmDel")
        self.horizontalLayout_Alarm2.addWidget(self.pushButton_AlarmDel)
        self.verticalLayout_Alarm.addLayout(self.horizontalLayout_Alarm2)
        self.horizontalLayout_Alarm1.addLayout(self.verticalLayout_Alarm)
        spacerItem4 = QtWidgets.QSpacerItem(39, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_Alarm1.addItem(spacerItem4)
        self.checkBox = QtWidgets.QCheckBox(parent=self.scrollAreaWidgetContents_Alarm)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.checkBox.setFont(font)
        self.checkBox.setText("")
        self.checkBox.setIconSize(QtCore.QSize(20, 20))
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout_Alarm1.addWidget(self.checkBox)
        self.verticalLayout_4.addLayout(self.horizontalLayout_Alarm1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 377, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem5)
        self.scrollArea_Alarm.setWidget(self.scrollAreaWidgetContents_Alarm)
        self.verticalLayout.addWidget(self.scrollArea_Alarm)
        self.horizontalLayout_20.addLayout(self.verticalLayout)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem6)
        self.verticalLayout_2.addLayout(self.horizontalLayout_20)
        spacerItem7 = QtWidgets.QSpacerItem(20, 21, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_2.addItem(spacerItem7)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Секундомер/Таймер"))
        self.pushButton_Alarm.setText(_translate("Dialog", "Будильник"))
        self.pushButton_Timer.setText(_translate("Dialog", "Таймер"))
        self.pushButton_Sec.setText(_translate("Dialog", "Секундомер"))
        self.pushButton_Alarm_add.setText(_translate("Dialog", "Добавить будильник"))
        self.label_name.setText(_translate("Dialog", "1"))
        self.pushButton_ch_Alarm.setText(_translate("Dialog", "PushButton_ch_Alatm"))
        self.label_d1.setText(_translate("Dialog", "Пн"))
        self.label_d2.setText(_translate("Dialog", "Вт"))
        self.label_d3.setText(_translate("Dialog", "Ср"))
        self.label_d4.setText(_translate("Dialog", "Чт"))
        self.label_d5.setText(_translate("Dialog", "Пн"))
        self.label_d6.setText(_translate("Dialog", "Сб"))
        self.label_d7.setText(_translate("Dialog", "Вс"))
        self.pushButton_AlarmDel.setText(_translate("Dialog", "Удалить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
