
from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(405, 188)
        # Таймер
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        
        self.pushButton_Timer = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_Timer.setObjectName("pushButton_Timer")
        self.horizontalLayout.addWidget(self.pushButton_Timer)
        self.pushButton_Sec = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_Sec.setObjectName("pushButton_Sec")
        self.horizontalLayout.addWidget(self.pushButton_Sec)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding,
                                            QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_h = QtWidgets.QLabel(parent=Dialog)
        self.label_h.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_h.setFont(font)
        self.label_h.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_h.setObjectName("label_h")
        self.horizontalLayout_2.addWidget(self.label_h)
        self.label_Timer_h = QtWidgets.QLabel(parent=Dialog)
        self.label_Timer_h.setObjectName("label_Timer_h")
        self.horizontalLayout_2.addWidget(self.label_Timer_h)
        self.label_min = QtWidgets.QLabel(parent=Dialog)
        self.label_min.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_min.setFont(font)
        self.label_min.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_min.setObjectName("label_min")
        self.horizontalLayout_2.addWidget(self.label_min)
        self.label_Timer_min = QtWidgets.QLabel(parent=Dialog)
        self.label_Timer_min.setObjectName("label_Timer_min")
        self.horizontalLayout_2.addWidget(self.label_Timer_min)
        self.label_sec = QtWidgets.QLabel(parent=Dialog)
        self.label_sec.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_sec.setFont(font)
        self.label_sec.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_sec.setObjectName("label_sec")
        self.horizontalLayout_2.addWidget(self.label_sec)
        self.label_Timer_sec = QtWidgets.QLabel(parent=Dialog)
        self.label_Timer_sec.setObjectName("label_Timer_sec")
        self.horizontalLayout_2.addWidget(self.label_Timer_sec)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_Timer_start_stop = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_Timer_start_stop.setAutoDefault(True)
        self.pushButton_Timer_start_stop.setDefault(False)
        self.pushButton_Timer_start_stop.setObjectName("pushButton_Timer_start_stop")
        self.horizontalLayout_4.addWidget(self.pushButton_Timer_start_stop)
        self.pushButton_Timer_reset = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_Timer_reset.setDefault(False)
        self.pushButton_Timer_reset.setObjectName("pushButton_Timer_reset")
        self.horizontalLayout_4.addWidget(self.pushButton_Timer_reset)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.pushButton_Timer_setTimer = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_Timer_setTimer.setObjectName("pushButton_Timer_setTimer")
        self.verticalLayout.addWidget(self.pushButton_Timer_setTimer)

        self.pushButton_Timer_music = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_Timer_music.setObjectName("pushButton_Timer_music")
        self.verticalLayout.addWidget(self.pushButton_Timer_music)
        self.pushButton_Timer_music.hide()

        spacerItem2 = QtWidgets.QSpacerItem(20, 17, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)

        # Секундомер
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_Sec_h_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_Sec_h_2.setMinimumSize(QtCore.QSize(60, 45))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_Sec_h_2.setFont(font)
        self.label_Sec_h_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_Sec_h_2.setObjectName("label_Sec_h_2")
        self.horizontalLayout_3.addWidget(self.label_Sec_h_2)
        self.label_Sec_h = QtWidgets.QLabel(parent=Dialog)
        self.label_Sec_h.setObjectName("label_Sec_h")
        self.horizontalLayout_3.addWidget(self.label_Sec_h)
        self.label_Sec_min_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_Sec_min_2.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_Sec_min_2.setFont(font)
        self.label_Sec_min_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_Sec_min_2.setObjectName("label_Sec_min_2")
        self.horizontalLayout_3.addWidget(self.label_Sec_min_2)
        self.label_Sec_min = QtWidgets.QLabel(parent=Dialog)
        self.label_Sec_min.setObjectName("label_Sec_min")
        self.horizontalLayout_3.addWidget(self.label_Sec_min)
        self.label_Sec_sec_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_Sec_sec_2.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_Sec_sec_2.setFont(font)
        self.label_Sec_sec_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_Sec_sec_2.setObjectName("label_Sec_sec_2")
        self.horizontalLayout_3.addWidget(self.label_Sec_sec_2)
        self.label_Sec_sec = QtWidgets.QLabel(parent=Dialog)
        self.label_Sec_sec.setObjectName("label_Sec_sec")
        self.horizontalLayout_3.addWidget(self.label_Sec_sec)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_Sec_start_stop = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_Sec_start_stop.setObjectName("pushButton_Sec_start_stop")
        self.horizontalLayout_2.addWidget(self.pushButton_Sec_start_stop)
        self.pushButton_Sec_reset = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_Sec_reset.setObjectName("pushButton_Sec_reset")
        self.horizontalLayout_2.addWidget(self.pushButton_Sec_reset)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pushButton_Sec_round = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_Sec_round.setObjectName("pushButton_Sec_round")
        self.verticalLayout.addWidget(self.pushButton_Sec_round)
        spacerItem2 = QtWidgets.QSpacerItem(20, 21, QtWidgets.QSizePolicy.Policy.Minimum,
                                            QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.list_sec_widget = [self.label_Sec_h_2, self.label_Sec_h, self.label_Sec_min_2,
                                self.label_Sec_min, self.label_Sec_sec_2, self.label_Sec_sec,
                                self.pushButton_Sec_start_stop, self.pushButton_Sec_reset,
                                self.pushButton_Sec_round]
        

        self.list_timer_widget = [self.label_h, self.label_Timer_h, self.label_min,
                                  self.label_Timer_min, self.label_sec, self.label_Timer_sec,
                                  self.pushButton_Timer_start_stop, self.pushButton_Timer_reset,
                                  self.pushButton_Timer_setTimer, self.pushButton_Timer_music]


        for i in self.list_sec_widget:
            i.hide()
            
        self.pushButton_Timer.setStyleSheet("background-color: #57e389;")
        self.pushButton_Sec.setStyleSheet("background-color: #f66151;")

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Секундомер/Таймер"))
        self.pushButton_Sec.setText(_translate("Dialog", "Секундомер"))
        self.pushButton_Timer.setText(_translate("Dialog", "Таймер"))
        self.label_h.setText(_translate("Dialog", "0"))
        self.label_Timer_h.setText(_translate("Dialog", "ч."))
        self.label_min.setText(_translate("Dialog", "0"))
        self.label_Timer_min.setText(_translate("Dialog", "мин."))
        self.label_sec.setText(_translate("Dialog", "0"))
        self.label_Timer_sec.setText(_translate("Dialog", "сек."))
        self.pushButton_Timer_start_stop.setText(_translate("Dialog", "Старт"))
        self.pushButton_Timer_reset.setText(_translate("Dialog", "Сброс"))
        self.pushButton_Timer_setTimer.setText(_translate("Dialog", "Задать время и мелодию"))
        self.pushButton_Timer_music.setText(_translate("Dialog", "Остановить музыку"))
        self.label_Sec_h_2.setText(_translate("Dialog", "0"))
        self.label_Sec_h.setText(_translate("Dialog", "ч."))
        self.label_Sec_min_2.setText(_translate("Dialog", "0"))
        self.label_Sec_min.setText(_translate("Dialog", "мин."))
        self.label_Sec_sec_2.setText(_translate("Dialog", "0"))
        self.label_Sec_sec.setText(_translate("Dialog", "сек."))
        self.pushButton_Sec_start_stop.setText(_translate("Dialog", "Старт"))
        self.pushButton_Sec_reset.setText(_translate("Dialog", "Сброс"))
        self.pushButton_Sec_round.setText(_translate("Dialog", "Круг"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
