# Основа секундомера


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(516, 500)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_Timer = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_Timer.setMinimumSize(QtCore.QSize(128, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_Timer.setFont(font)
        self.pushButton_Timer.setStyleSheet("background-color: rgb(192, 191, 188);")
        self.pushButton_Timer.setObjectName("pushButton_Timer")
        self.horizontalLayout.addWidget(self.pushButton_Timer)
        self.pushButton_Sec = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_Sec.setMinimumSize(QtCore.QSize(128, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_Sec.setFont(font)
        self.pushButton_Sec.setObjectName("pushButton_Sec")
        self.horizontalLayout.addWidget(self.pushButton_Sec)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_Sec_h_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_Sec_h_2.setMinimumSize(QtCore.QSize(60, 45))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_Sec_h_2.setFont(font)
        self.label_Sec_h_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_Sec_h_2.setObjectName("label_Sec_h_2")
        self.horizontalLayout_3.addWidget(self.label_Sec_h_2)
        self.label_Sec_h = QtWidgets.QLabel(parent=Dialog)
        self.label_Sec_h.setObjectName("label_Sec_h")
        self.horizontalLayout_3.addWidget(self.label_Sec_h)
        self.label_Sec_min_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_Sec_min_2.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_Sec_min_2.setFont(font)
        self.label_Sec_min_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_Sec_min_2.setObjectName("label_Sec_min_2")
        self.horizontalLayout_3.addWidget(self.label_Sec_min_2)
        self.label_Sec_min = QtWidgets.QLabel(parent=Dialog)
        self.label_Sec_min.setObjectName("label_Sec_min")
        self.horizontalLayout_3.addWidget(self.label_Sec_min)
        self.label_Sec_sec_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_Sec_sec_2.setMinimumSize(QtCore.QSize(60, 0))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_Sec_sec_2.setFont(font)
        self.label_Sec_sec_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_Sec_sec_2.setObjectName("label_Sec_sec_2")
        self.horizontalLayout_3.addWidget(self.label_Sec_sec_2)
        self.label_Sec_sec = QtWidgets.QLabel(parent=Dialog)
        self.label_Sec_sec.setObjectName("label_Sec_sec")
        self.horizontalLayout_3.addWidget(self.label_Sec_sec)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_Sec_start_stop = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_Sec_start_stop.setMinimumSize(QtCore.QSize(140, 40))
        self.pushButton_Sec_start_stop.setObjectName("pushButton_Sec_start_stop")
        self.horizontalLayout_2.addWidget(self.pushButton_Sec_start_stop)
        self.pushButton_Sec_reset = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_Sec_reset.setMinimumSize(QtCore.QSize(140, 40))
        self.pushButton_Sec_reset.setObjectName("pushButton_Sec_reset")
        self.horizontalLayout_2.addWidget(self.pushButton_Sec_reset)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pushButton_Sec_round = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_Sec_round.setMinimumSize(QtCore.QSize(99, 35))
        self.pushButton_Sec_round.setObjectName("pushButton_Sec_round")
        self.verticalLayout.addWidget(self.pushButton_Sec_round)
        self.horizontalLayout_50 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_50.setObjectName("horizontalLayout_50")
        self.label50 = QtWidgets.QLabel(parent=Dialog)
        self.label50.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label50.setObjectName("label50")
        self.horizontalLayout_50.addWidget(self.label50)
        self.label51 = QtWidgets.QLabel(parent=Dialog)
        self.label51.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label51.setObjectName("label51")
        self.horizontalLayout_50.addWidget(self.label51)
        self.label52 = QtWidgets.QLabel(parent=Dialog)
        self.label52.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label52.setObjectName("label52")
        self.horizontalLayout_50.addWidget(self.label52)
        self.verticalLayout.addLayout(self.horizontalLayout_50)
        self.scrollArea = QtWidgets.QScrollArea(parent=Dialog)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 250))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 354, 248))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout_20.addLayout(self.verticalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_20)
        spacerItem4 = QtWidgets.QSpacerItem(20, 21, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Секундомер/Таймер"))
        self.pushButton_Timer.setText(_translate("Dialog", "Таймер"))
        self.pushButton_Sec.setText(_translate("Dialog", "Секундомер"))
        self.label_Sec_h_2.setText(_translate("Dialog", "0"))
        self.label_Sec_h.setText(_translate("Dialog", "ч."))
        self.label_Sec_min_2.setText(_translate("Dialog", "0"))
        self.label_Sec_min.setText(_translate("Dialog", "мин."))
        self.label_Sec_sec_2.setText(_translate("Dialog", "0"))
        self.label_Sec_sec.setText(_translate("Dialog", "сек."))
        self.pushButton_Sec_start_stop.setText(_translate("Dialog", "Старт"))
        self.pushButton_Sec_reset.setText(_translate("Dialog", "Сброс"))
        self.pushButton_Sec_round.setText(_translate("Dialog", "Круг"))
        self.label50.setText(_translate("Dialog", "Общее время"))
        self.label51.setText(_translate("Dialog", "Время круга"))
        self.label52.setText(_translate("Dialog", "Круги"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
