# Основа таймера

from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(516, 500)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_Timer = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_Timer.setMinimumSize(QtCore.QSize(128, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_Timer.setFont(font)
        self.pushButton_Timer.setStyleSheet("")
        self.pushButton_Timer.setObjectName("pushButton_Timer")
        self.horizontalLayout.addWidget(self.pushButton_Timer)
        self.pushButton_Sec = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_Sec.setMinimumSize(QtCore.QSize(128, 36))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pushButton_Sec.setFont(font)
        self.pushButton_Sec.setObjectName("pushButton_Sec")
        self.horizontalLayout.addWidget(self.pushButton_Sec)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_h = QtWidgets.QLabel(parent=Dialog)
        self.label_h.setMinimumSize(QtCore.QSize(60, 45))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_h.setFont(font)
        self.label_h.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_h.setObjectName("label_h")
        self.horizontalLayout_2.addWidget(self.label_h)
        self.label_Timer_h = QtWidgets.QLabel(parent=Dialog)
        self.label_Timer_h.setObjectName("label_Timer_h")
        self.horizontalLayout_2.addWidget(self.label_Timer_h)
        self.label_min = QtWidgets.QLabel(parent=Dialog)
        self.label_min.setMinimumSize(QtCore.QSize(60, 45))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_min.setFont(font)
        self.label_min.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_min.setObjectName("label_min")
        self.horizontalLayout_2.addWidget(self.label_min)
        self.label_Timer_min = QtWidgets.QLabel(parent=Dialog)
        self.label_Timer_min.setObjectName("label_Timer_min")
        self.horizontalLayout_2.addWidget(self.label_Timer_min)
        self.label_sec = QtWidgets.QLabel(parent=Dialog)
        self.label_sec.setMinimumSize(QtCore.QSize(60, 45))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_sec.setFont(font)
        self.label_sec.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_sec.setObjectName("label_sec")
        self.horizontalLayout_2.addWidget(self.label_sec)
        self.label_Timer_sec = QtWidgets.QLabel(parent=Dialog)
        self.label_Timer_sec.setObjectName("label_Timer_sec")
        self.horizontalLayout_2.addWidget(self.label_Timer_sec)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_Timer_start_stop = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_Timer_start_stop.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_Timer_start_stop.setAutoDefault(True)
        self.pushButton_Timer_start_stop.setDefault(False)
        self.pushButton_Timer_start_stop.setObjectName("pushButton_Timer_start_stop")
        self.horizontalLayout_4.addWidget(self.pushButton_Timer_start_stop)
        self.pushButton_Timer_reset = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_Timer_reset.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_Timer_reset.setDefault(False)
        self.pushButton_Timer_reset.setObjectName("pushButton_Timer_reset")
        self.horizontalLayout_4.addWidget(self.pushButton_Timer_reset)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.pushButton_Timer_setTimer = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_Timer_setTimer.setMinimumSize(QtCore.QSize(99, 35))
        self.pushButton_Timer_setTimer.setObjectName("pushButton_Timer_setTimer")
        self.verticalLayout.addWidget(self.pushButton_Timer_setTimer)
        self.horizontalLayout_20.addLayout(self.verticalLayout)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_20)
        spacerItem4 = QtWidgets.QSpacerItem(20, 43, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Секундомер/Таймер"))
        self.pushButton_Timer.setText(_translate("Dialog", "Таймер"))
        self.pushButton_Sec.setText(_translate("Dialog", "Секундомер"))
        self.label_h.setText(_translate("Dialog", "0"))
        self.label_Timer_h.setText(_translate("Dialog", "ч."))
        self.label_min.setText(_translate("Dialog", "0"))
        self.label_Timer_min.setText(_translate("Dialog", "мин."))
        self.label_sec.setText(_translate("Dialog", "0"))
        self.label_Timer_sec.setText(_translate("Dialog", "сек."))
        self.pushButton_Timer_start_stop.setText(_translate("Dialog", "Старт"))
        self.pushButton_Timer_reset.setText(_translate("Dialog", "Сброс"))
        self.pushButton_Timer_setTimer.setText(_translate("Dialog", "Задать время и мелодию"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
