# Form implementation generated from reading ui file 'Sec2.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import pyqtSignal, QUrl, Qt
from PyQt6.QtMultimedia import QMediaPlayer, QAudioOutput
from PyQt6.QtWidgets import QDialog, QVBoxLayout, QLabel, QPushButton


class Ui_Form(QDialog):
    value_selected = pyqtSignal(tuple)  # Определение сигнала

    def __init__(self):
        super().__init__()
        self.resize(261, 245)
        self.setWindowFlags(QtCore.Qt.WindowType.SubWindow)
        self.verticalLayout = QtWidgets.QVBoxLayout(self)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.timeEdit = QtWidgets.QTimeEdit(self)
        font = QtGui.QFont()
        font.setPointSize(29)
        self.timeEdit.setFont(font)
        self.timeEdit.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.timeEdit.setMinimumDate(QtCore.QDate(2000, 1, 5))
        self.timeEdit.setObjectName("timeEdit")
        self.verticalLayout.addWidget(self.timeEdit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton = QtWidgets.QRadioButton(self)
        self.radioButton.setMaximumSize(QtCore.QSize(40, 16777215))
        self.radioButton.setText("")
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.label_2 = QtWidgets.QLabel(self)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton_2 = QtWidgets.QRadioButton(self)
        self.radioButton_2.setMaximumSize(QtCore.QSize(40, 16777215))
        self.radioButton_2.setText("")
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_2.addWidget(self.radioButton_2)
        self.label_3 = QtWidgets.QLabel(self)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.radioButton_3 = QtWidgets.QRadioButton(self)
        self.radioButton_3.setMaximumSize(QtCore.QSize(40, 16777215))
        self.radioButton_3.setText("")
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_3.addWidget(self.radioButton_3)
        self.label_4 = QtWidgets.QLabel(self)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.pushButton = QtWidgets.QPushButton(self)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self)
        self.pushButton.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.media_player = QMediaPlayer(self)

        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)
        # предустановленная мелодия
        self.music = '1.mp3'
        # вызовы на кнопки
        self.pushButton.clicked.connect(self.handle_button_click)  # выход из настроек
        self.pushButton_2.clicked.connect(self.music_stop)  # выход из настроек
        # self.radioButton.clicked.connect(self.play_music)  # выбор мелодии 1
        # self.radioButton_2.clicked.connect(self.play_music_2)  # выбор мелодии 2
        # self.radioButton_3.clicked.connect(self.play_music_3)  # выбор мелодии 3
        self.radioButton.clicked.connect(self.open_modal)
        self.radioButton_2.clicked.connect(self.open_modal)
        self.radioButton_3.clicked.connect(self.open_modal)



    def handle_button_click(self):
        # смотрим какая radioButton выбрана
        a = (self.radioButton, self.radioButton_2, self.radioButton_3)
        for i, j in enumerate(a):
            if j.isChecked():
                value = i

        selected_value = (self.timeEdit.time().hour(), self.timeEdit.time().minute(), self.timeEdit.time().second(), value)  # Ваше выбранное значение
        self.value_selected.emit(selected_value)  # Испускание сигнала с передачей значения
        self.accept()  # Закрываем окно

    def play_music(self):
        self.music = '1.mp3'
    def play_music_2(self):
        self.music = '2.mp3'
    def play_music_3(self):
        self.music = '3.mp3'
    
    def music_stop(self):
        self.player.stop()
        self.pushButton.setEnabled(True)
        self.radioButton.setEnabled(True)
        self.radioButton_2.setEnabled(True)
        self.radioButton_3.setEnabled(True)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Настройки"))
        self.label.setText(_translate("Form", "Задайте время таймера"))
        self.timeEdit.setDisplayFormat(_translate("Form", "HH:mm:ss"))
        self.label_2.setText(_translate("Form", "Звоночек1"))
        self.label_3.setText(_translate("Form", "Звоночек2"))
        self.label_4.setText(_translate("Form", "Звоночек3"))
        self.pushButton.setText(_translate("Form", "Подтвердить"))
        self.pushButton_2.setText(_translate("Form", "Стоп"))


    # Вызов модального окна проигрования музыки с передачей имени проигруемого файла
    def open_modal(self):
        # dialog = ModalDialog(self)
        # dialog.play_audio(self.music)
        # dialog.exec()

        file_path = self.music  # "path/to/your/file.mp3"  # Путь к вашему MP3-файлу
        self.player = QMediaPlayer(self)
        self.audio_output = QAudioOutput(self)
        self.player.setAudioOutput(self.audio_output)
        self.player.setSource(QUrl.fromLocalFile(file_path))
        self.audio_output.setVolume(50)
        self.player.play()  # Воспроизведение аудио
        self.player.mediaStatusChanged.connect(self.handle_media_status)
        self.pushButton.setEnabled(False)
        self.radioButton.setEnabled(False)
        self.radioButton_2.setEnabled(False)
        self.radioButton_3.setEnabled(False)


    # Проверяем статус воспроизведения музыки(если музыка закончилась - разблокируем кнопки)
    def handle_media_status(self, status):
        if status == QMediaPlayer.MediaStatus.EndOfMedia:

            self.pushButton.setEnabled(True)
            self.radioButton.setEnabled(True)
            self.radioButton_2.setEnabled(True)
            self.radioButton_3.setEnabled(True)




if __name__ == '__main__':
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = Ui_Form()
    window.show()
    sys.exit(app.exec())